defaults:
  team_set: modern_replays_v2
  battle_backend: metamon
  checkpoints: [null]
  temperatures: [1.0, 1.2, 1.3, 1.5, 1.75, 2.0, 2.25]
  num_agents: 1

agents:
  SynRLV0:
    model_name: SyntheticRLV0
    checkpoints: [null]
    num_agents: 1

  SynRLV1:
    model_name: SyntheticRLV1
    checkpoints: [null]
    num_agents: 1 
  
  SynRLV1_PlusPlus:
    model_name: SyntheticRLV1_PlusPlus
    checkpoints: [null]
    num_agents: 1

  PAC-MM-SynRLV2:
    model_name: SyntheticRLV2
    checkpoints: [null, 32, 36, 34]
    num_agents: 5
  
  PAC-MM-Kadabra:
    model_name: Kadabra
  
  PAC-MM-SmallILFA:
    model_name: SmallILFA
    checkpoints: [2]
    num_agents: 2
  
  PAC-MM-Minikazam:
    model_name: Minikazam

  PAC-MM-Alakazam:
    model_name: Alakazam2
    checkpoints: [40, 48, 36, 32]
    num_agents: 2
  
  PAC-MM-Wildcard:
    model_name: Alakazam3
    checkpoints: [10, 12, 20, 22, 14]
    num_agents: 4
  
  PAC-MM-Mystery:
    model_name: Alakazam4
    checkpoints: [30, 40, 48, 50, 52, 32]
    num_agents: 4
